### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jcrossguitar** [jcrossguitar/ucsd_bootcamp_project_1#8]
- [ ] CORB error I am getting with my api key for google places needs to be resolved. I was doing some research on the way to fix, but did not get very far yesterday once class ended. 

- [ ] We need to figure out what has to be done with Youtube in order to get their videos to appear on our pages. Even having the code present without displaying the video itself is a step forward. 

- [ ] I think our CSS can have a very simple/general layout that uses the same colors and formats over and over again. Think background colors, font-size, margins/borders/padding. I suck at matching colors, so someone else will need to step up for eye catching design.

- [ ] Remember KISS (keep it simple stupid) method.
